name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add your other dependencies here
  
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  provider: ^6.1.2
  uuid: ^4.4.0
  weather_icons: ^3.0.0
  google_maps_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/Lato-Regular.ttf

  assets:
    - .env
  uses-material-design: true
